# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 杨鑫磊的博客
email: yangxinlei007@live.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎访问我的博客，转载请注明。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yangxinlei.github.io/" # the base hostname & protocol for your site
twitter_username: nil
github_username:  yangxinlei

# Build settings
markdown: kramdown
